name: hello-world
on:
  push:
  workflow_dispatch:
    inputs:
      manual_op:
        description: 'Specify the statement to print'
        required: true
        default: 'Hello World'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "${{github.event.inputs.manual_op}}"
